# Generated by Django 3.1.1 on 2020-09-23 18:57

from django.db import migrations, models
import myapp.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canadian',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('40ff6e56-39a3-4b13-b55b-8242ce8cc88b'), primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=70)),
                ('last', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, validators=[myapp.validators.validatePhone])),
                ('profile', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('occupation', models.CharField(max_length=70)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
