# Generated by Django 3.1.1 on 2020-09-23 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canadian',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='canadian',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='canadian',
            name='id',
            field=models.UUIDField(default=uuid.UUID('198e00f7-8843-490a-b712-780ae7f282f5'), primary_key=True, serialize=False),
        ),
    ]
