# Generated by Django 3.1.1 on 2020-09-23 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200923_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canadian',
            old_name='first',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='canadian',
            old_name='last',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='canadian',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e61c2e55-08e7-463c-b4b4-27f23c22c638'), primary_key=True, serialize=False),
        ),
    ]
