# Generated by Django 3.1.1 on 2020-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200929_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadian',
            name='rate',
            field=models.IntegerField(default=3),
        ),
    ]
