# Generated by Django 3.1.1 on 2020-09-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20200929_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='canadian',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='canadian', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OridnaryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[myapp.validators.validatePhone])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('profile', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oridnaryUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
