# Generated by Django 3.1.1 on 2020-10-01 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200929_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canadian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='canadian',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='canadian',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='oridnaryuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
