# Generated by Django 3.1.1 on 2020-10-02 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201001_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startAt', models.DateTimeField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('endAt', models.DateTimeField(null=True)),
                ('isFinish', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('canadian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.canadian')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.oridnaryuser')),
            ],
        ),
    ]
