# Generated by Django 3.1.1 on 2020-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='startAt',
            field=models.DateTimeField(null=True),
        ),
    ]
