# Generated by Django 3.1.1 on 2020-10-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201002_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
